# -*- coding: utf-8 -*-
"""Memory_scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_vQdlqBj2f88018gSOYFfuTC10ByknVi
"""

!pip install selenium
!pip install Pillow

import requests

# solicitud HTTP a la página
url = "https://www.memorykings.pe/listados/1028/laptops-intel-celeron-empresarial"
response = requests.get(url)

# fue exitosa?
if response.status_code == 200:
    # Obtener el HTML de la página
    html_content = response.text
    print(html_content)
else:
    print("Error al cargar la página:", response.status_code)

from bs4 import BeautifulSoup
import requests
import csv

# obtengo URLs de las subcategorías de laptops
url = "https://www.memorykings.pe/subcategorias/19/laptops"
response = requests.get(url)

if response.status_code == 200:
    #  HTML de la página
    html_content = response.text
    soup = BeautifulSoup(html_content, "html.parser")

    # busco los enlaces de subcategorías de laptops
    links = soup.find('ul', class_='products').find_all('a')

    # Crear un archivo CSV y escribir los encabezados
    with open('productos_laptops.csv', mode='w', newline='', encoding='utf-8') as file:
        writer = csv.writer(file)
        writer.writerow(['Nombre del producto', 'Precio'])

        # Itero sobre las subcategorías
        for link in links:
            # Construir la URL completa de la subcategoría
            href = link.get('href')
            full_url = "https://www.memorykings.pe" + href

            # obtengo info de los productos de la subcategoría
            subcategoria_response = requests.get(full_url)
            if subcategoria_response.status_code == 200:
                subcategoria_html_content = subcategoria_response.text
                subcategoria_soup = BeautifulSoup(subcategoria_html_content, "html.parser")

                # Busco todos los elementos de productos
                productos = subcategoria_soup.find_all("div", class_="content")

                # busco cantidad de productos
                num_productos_tag = subcategoria_soup.find("div", class_="header-products").find("b")
                if num_productos_tag:
                    num_productos = int(num_productos_tag.text)
                else:
                    num_productos = 0

                # Itero sobre los productos y extraigo info
                for i in range(num_productos):
                    # Nombre del producto
                    nombre_producto = productos[i].find("h4").text.strip()

                    # Precio del producto
                    precio = productos[i].find("div", class_="price").text.strip()

                    # Escribir en el CSV
                    writer.writerow([nombre_producto, precio])

                    print("Nombre del producto:", nombre_producto)
                    print("Precio:", precio)
                    print("-" * 30)
            else:
                print("Error al cargar la página de la subcategoría:", subcategoria_response.status_code)
else:
    print("Error al cargar la página de las subcategorías de laptops:", response.status_code)

print("Los datos se han guardado correctamente en 'productos_laptops.csv'")

import pandas as pd
df=pd.read_csv('productos_laptops.csv')
df